### ISSUE TITLE
Guide only covers embedded mode

### ISSUE THREAD

**Issue by cangencer** [hazelcast-guides/hazelcast-embedded-microprofile#16]
Embedded mode of Hazelcast is only applicable for some very narrow use cases - I would prefer the guide would be using client/server mode by default.

**Comment by enozcan** [comment]
Now it covers client/server as the default mode by #18.

**Comment by cangencer** [comment]
@enozcan nice! would it make sense to rename the URL? since it has "embedded' in it ?

**Comment by enozcan** [comment]
Sure it does. But I afraid I need to check other guides to see if there is a link to this guide - as we construct urls with repo names. It's not a big deal to replace all occurrences but let me check if there is any other issue to be considered when url/repo name is changed.
